[package]
name = "rd-ndk"
description = "RustyDroid: ELF loader x86_64 + interpretador ARM (feature-gated)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
