# workspace próprio (padrão cargo-fuzz: fora do workspace principal)
[workspace]

[package]
name = "rd-dex-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.rd-dex]
path = ".."

[[bin]]
name = "dex"
path = "fuzz_targets/dex.rs"
test = false
doc = false
bench = false
